apiVersion: v1
kind: Service
metadata:
  name: fault-tolerance
  namespace: core
  labels:
    app: fault-tolerance
spec:
  type: NodePort
  selector:
    app: fault-tolerance
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 8080
      nodePort: 30081

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fault-tolerance
  name: fault-tolerance
  namespace: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fault-tolerance
  template:
    metadata:
      labels:
        app: fault-tolerance
    spec:
      containers:
        - image: fault-tolerance:latest
          name: fault-tolerance
          imagePullPolicy: Never
          ports:
            - containerPort: 8080