rate.service.url=https://httpbin.org/status/{status}


management.endpoints.web.exposure.include=*

#resilience4j.circuitbreaker.instances.rateService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.rateService.slidingWindowSize=100
resilience4j.circuitbreaker.instances.rateService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.rateService.minimumNumberOfCalls=100
resilience4j.circuitbreaker.instances.rateService.recordExceptions=org.springframework.web.client.HttpServerErrorException

resilience4j.retry.instances.rateService.maxAttempts=3
resilience4j.retry.instances.rateService.waitDuration=10s
resilience4j.retry.instances.rateService.enableExponentialBackoff=false
resilience4j.retry.instances.rateService.exponentialBackoffMultiplier=2
resilience4j.retry.instances.rateService.retryExceptions=org.springframework.web.client.HttpServerErrorException,java.io.IOException

resilience4j.bulkhead.instances.rateService.maxWaitDuration=10ms
resilience4j.bulkhead.instances.rateService.maxConcurrentCalls=10
